In [1]:
import pandas as pd
import numpy as np
import re
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
# Path to the folder where CSV files are stored
folder_path = '../../data/source_data/atp'

# Create a list of files in the specified folder that have a .csv extension
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

dataframes = []  # Create an empty list to store DataFrames

# Loop through each CSV file and add it to the list
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    # print(len(df))
    dataframes.append(df)

# Concatenate all DataFrames into a single DataFrame
data_atp = pd.concat(dataframes, ignore_index=True)

In [3]:
data_atp.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2015-339,Brisbane,Hard,28,A,20150104,1,105357,NaN,WC,John Millman,R,183.0,AUS,25.5,105733,NaN,Q,Rhyne Williams,R,185.0,USA,23.7,6-3 6-1,3,R32,65.0,6.0,2.0,44.0,24.0,19.0,14.0,8.0,1.0,1.0,3.0,4.0,50.0,31.0,20.0,5.0,8.0,1.0,5.0,153.0,328.0,220.0,221.0
1,2015-339,Brisbane,Hard,28,A,20150104,2,103813,NaN,NaN,Jarkko Nieminen,L,185.0,FIN,33.4,106045,NaN,Q,Denis Kudla,R,180.0,USA,22.3,4-6 6-1 6-4,3,R32,104.0,4.0,0.0,92.0,59.0,39.0,17.0,14.0,4.0,7.0,6.0,1.0,83.0,50.0,26.0,19.0,13.0,3.0,8.0,73.0,689.0,123.0,440.0
2,2015-339,Brisbane,Hard,28,A,20150104,3,105902,NaN,WC,James Duckworth,R,183.0,AUS,22.9,104468,6.0,NaN,Gilles Simon,R,183.0,FRA,30.0,6-2 6-2,3,R32,68.0,4.0,0.0,45.0,27.0,20.0,11.0,8.0,2.0,3.0,2.0,1.0,56.0,37.0,22.0,5.0,8.0,10.0,15.0,125.0,430.0,21.0,1730.0
3,2015-339,Brisbane,Hard,28,A,20150104,4,104871,NaN,NaN,Jeremy Chardy,R,188.0,FRA,27.8,104979,NaN,NaN,Andrey Golubev,R,185.0,KAZ,27.4,6-4 6-4,3,R32,69.0,7.0,1.0,53.0,39.0,31.0,11.0,10.0,0.0,0.0,9.0,2.0,57.0,38.0,30.0,8.0,10.0,1.0,3.0,31.0,1195.0,72.0,691.0
4,2015-339,Brisbane,Hard,28,A,20150104,5,105373,NaN,NaN,Martin Klizan,L,190.0,SVK,25.4,103781,NaN,NaN,Jurgen Melzer,L,183.0,AUT,33.6,6-7(5) 7-6(6) 6-1,3,R32,144.0,9.0,4.0,130.0,79.0,55.0,27.0,16.0,6.0,8.0,4.0,4.0,95.0,62.0,40.0,19.0,15.0,4.0,8.0,34.0,1094.0,110.0,505.0

In [4]:
len(data_atp)

153959

In [5]:
data_atp.isnull().sum()

tourney_id                 0
tourney_name               0
surface                   53
draw_size                  0
tourney_level              0
tourney_date               0
match_num                  0
winner_id                  0
winner_seed            84236
winner_entry          132226
winner_name                0
winner_hand               14
winner_ht              17910
winner_ioc                16
winner_age                30
loser_id                   0
loser_seed            113863
loser_entry           115880
loser_name                 0
loser_hand                69
loser_ht               30346
loser_ioc                 13
loser_age                251
score                     15
best_of                    0
round                      0
minutes                11548
w_ace                   6321
w_df                    6321
w_svpt                  6321
w_1stIn                 6321
w_1stWon                6321
w_2ndWon                6321
w_SvGms                 6319
w_bpSaved               6321
w_bpFaced               6321
l_ace                   6321
l_df                    6321
l_svpt                  6321
l_1stIn                 6321
l_1stWon                6321
l_2ndWon                6321
l_SvGms                 6319
l_bpSaved               6320
l_bpFaced               6320
winner_rank             1228
winner_rank_points      1242
loser_rank              4942
loser_rank_points       4957
dtype: int64

In [6]:
data_atp.dropna(subset=['w_ace'], inplace=True, ignore_index=True) # Delete rows where there is no data for 'w_ace' (match stats)
len(data_atp)

147638

In [7]:
data_atp.isnull().sum()

tourney_id                 0
tourney_name               0
surface                    0
draw_size                  0
tourney_level              0
tourney_date               0
match_num                  0
winner_id                  0
winner_seed            79700
winner_entry          126185
winner_name                0
winner_hand               10
winner_ht              17084
winner_ioc                16
winner_age                25
loser_id                   0
loser_seed            108676
loser_entry           109994
loser_name                 0
loser_hand                51
loser_ht               28863
loser_ioc                 13
loser_age                239
score                      0
best_of                    0
round                      0
minutes                 6027
w_ace                      0
w_df                       0
w_svpt                     0
w_1stIn                    0
w_1stWon                   0
w_2ndWon                   0
w_SvGms                    0
w_bpSaved                  0
w_bpFaced                  0
l_ace                      0
l_df                       0
l_svpt                     0
l_1stIn                    0
l_1stWon                   0
l_2ndWon                   0
l_SvGms                    0
l_bpSaved                  0
l_bpFaced                  0
winner_rank             1010
winner_rank_points      1024
loser_rank              4414
loser_rank_points       4429
dtype: int64

In [8]:
data_atp['tourney_level'].unique()

array(['A', 'G', 'M', 'F', 'C', 'D'], dtype=object)

In [9]:
filtered_df = data_atp[data_atp['tourney_level'] == 'D']
filtered_df.head(10)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
18442,2016-M-DC-2016-G1-AM-M-BAR-ECU-01,Davis Cup G1 R1: BAR vs ECU,Clay,4,D,20160304,1,105877,NaN,NaN,Emilio Gomez,R,185.0,ECU,24.2,200618,NaN,NaN,Adam Hornby,NaN,NaN,BAR,20.6,6-0 6-0 6-0,5,RR,78.0,2.0,2.0,55.0,34.0,29.0,10.0,9.0,2.0,2.0,2.0,5.0,53.0,36.0,11.0,4.0,9.0,7.0,16.0,327.0,143.0,NaN,NaN
18443,2016-M-DC-2016-G1-AM-M-BAR-ECU-01,Davis Cup G1 R1: BAR vs ECU,Clay,4,D,20160304,2,105111,NaN,NaN,Ivan Endara,R,NaN,ECU,27.9,105985,NaN,NaN,Darian King,R,188.0,BAR,23.8,6-1 6-2 6-4,5,RR,149.0,0.0,3.0,87.0,62.0,45.0,13.0,13.0,7.0,9.0,0.0,2.0,86.0,53.0,29.0,11.0,12.0,6.0,13.0,395.0,108.0,243.0,217.0
18444,2016-M-DC-2016-G1-AM-M-BAR-ECU-01,Davis Cup G1 R1: BAR vs ECU,Clay,4,D,20160304,4,105877,NaN,NaN,Emilio Gomez,R,185.0,ECU,24.2,108786,NaN,NaN,Seanon Williams,R,NaN,BAR,25.0,6-0 6-2,3,RR,50.0,3.0,1.0,37.0,23.0,21.0,8.0,7.0,0.0,0.0,0.0,7.0,37.0,22.0,9.0,5.0,7.0,0.0,5.0,327.0,143.0,NaN,NaN
18445,2016-M-DC-2016-G1-AM-M-BAR-ECU-01,Davis Cup G1 R1: BAR vs ECU,Clay,4,D,20160304,5,105111,NaN,NaN,Ivan Endara,R,NaN,ECU,27.9,200618,NaN,NaN,Adam Hornby,NaN,NaN,BAR,20.6,6-0 6-1,3,RR,48.0,3.0,0.0,39.0,22.0,17.0,11.0,7.0,0.0,0.0,0.0,3.0,32.0,20.0,7.0,3.0,6.0,1.0,6.0,395.0,108.0,NaN,NaN
18446,2016-M-DC-2016-G1-AM-M-CHI-DOM-01,Davis Cup G1 R1: CHI vs DOM,Clay,4,D,20160304,1,105070,NaN,NaN,Hans Podlipnik Castillo,R,183.0,CHI,28.1,144773,NaN,NaN,Jose Olivares,NaN,NaN,DOM,19.1,6-1 6-1 7-6(4),5,RR,128.0,0.0,2.0,86.0,55.0,47.0,15.0,13.0,2.0,3.0,3.0,4.0,95.0,64.0,37.0,14.0,13.0,10.0,16.0,198.0,267.0,1250.0,6.0
18447,2016-M-DC-2016-G1-AM-M-CHI-DOM-01,Davis Cup G1 R1: CHI vs DOM,Clay,4,D,20160304,2,106174,NaN,NaN,Gonzalo Lama,R,180.0,CHI,22.8,105497,NaN,NaN,Jose Hernandez,R,183.0,DOM,25.9,6-3 7-6(3) 7-5,5,RR,133.0,4.0,1.0,104.0,72.0,57.0,18.0,17.0,3.0,4.0,3.0,4.0,100.0,75.0,55.0,10.0,16.0,5.0,8.0,263.0,199.0,222.0,234.0
18448,2016-M-DC-2016-G1-AM-M-CHI-DOM-01,Davis Cup G1 R1: CHI vs DOM,Clay,4,D,20160304,4,106426,NaN,NaN,Cristian Garin,R,185.0,CHI,19.7,136704,NaN,NaN,Manuel Castellanos,R,NaN,DOM,19.5,6-1 6-2,3,RR,47.0,7.0,2.0,35.0,17.0,16.0,13.0,8.0,0.0,1.0,0.0,4.0,53.0,36.0,19.0,5.0,7.0,4.0,9.0,383.0,116.0,NaN,NaN
18449,2016-M-DC-2016-G1-AM-M-CHI-DOM-01,Davis Cup G1 R1: CHI vs DOM,Clay,4,D,20160304,5,106174,NaN,NaN,Gonzalo Lama,R,180.0,CHI,22.8,144773,NaN,NaN,Jose Olivares,NaN,NaN,DOM,19.1,6-4 6-0,3,RR,58.0,1.0,0.0,47.0,32.0,24.0,11.0,8.0,4.0,4.0,1.0,0.0,51.0,34.0,17.0,9.0,8.0,2.0,6.0,263.0,199.0,1250.0,6.0
18450,2016-M-DC-2016-G1-EPA-M-HUN-ISR-01,Davis Cup G1 R1: HUN vs ISR,Clay,4,D,20160304,1,105954,NaN,NaN,Peter Nagy,R,180.0,HUN,23.9,104534,NaN,NaN,Dudi Sela,R,175.0,ISR,30.9,6-2 6-3 4-6 4-6 6-1,5,RR,179.0,2.0,5.0,124.0,71.0,46.0,32.0,22.0,8.0,15.0,2.0,4.0,134.0,84.0,41.0,23.0,22.0,8.0,19.0,612.0,50.0,89.0,613.0
18451,2016-M-DC-2016-G1-EPA-M-HUN-ISR-01,Davis Cup G1 R1: HUN vs ISR,Clay,4,D,20160304,2,105916,NaN,NaN,Marton Fucsovics,R,188.0,HUN,24.0,104804,NaN,NaN,Amir Weintraub,R,188.0,ISR,29.4,6-4 6-2 7-5,5,RR,106.0,10.0,2.0,89.0,62.0,43.0,14.0,15.0,4.0,7.0,1.0,1.0,82.0,49.0,30.0,12.0,15.0,5.0,12.0,203.0,260.0,197.0,267.0

In [10]:
len(filtered_df)

1239

In [11]:
# Remove records where 'tourney_level' is 'D' (Davis Cup), as we consider the Davis Cup a friendly tournament
data_atp = data_atp.loc[data_atp['tourney_level'] != 'D']
len(data_atp)

146399

In [12]:
# The NextGen Finals tournament is not a standard tournament, so we are not interested in those records
# Remove records where 'tourney_name' is 'NextGen Finals', as it has a non-standard structure
data_atp = data_atp.loc[data_atp['tourney_name'] != 'NextGen Finals']
len(data_atp)

146308

In [13]:
# We are not interested in the players' nationality, ID, or match number
data_atp.drop(columns=['winner_ioc', 'loser_ioc', 'match_num', 'winner_id', 'loser_id'], inplace=True)

In [14]:
data_atp['winner_entry'].unique()

array(['WC', nan, 'Q', 'LL', 'PR', 'SE', 'Alt', 'ALT', 'S', 'AL', '3)',
       '1)', '6)', '6) A', '2) A', 'ITF', 'P', 'I', 'A'], dtype=object)

In [15]:
# There are too many irrelevant categories in the columns 'winner_entry' and 'loser_entry', and we also do not need 'tourney_id'
data_atp.drop(columns=['winner_entry', 'loser_entry', 'tourney_id'], inplace=True)
data_atp.isnull().sum()

tourney_name               0
surface                    0
draw_size                  0
tourney_level              0
tourney_date               0
winner_seed            78461
winner_name                0
winner_hand                7
winner_ht              16932
winner_age                24
loser_seed            107437
loser_name                 0
loser_hand                27
loser_ht               28560
loser_age                235
score                      0
best_of                    0
round                      0
minutes                 5945
w_ace                      0
w_df                       0
w_svpt                     0
w_1stIn                    0
w_1stWon                   0
w_2ndWon                   0
w_SvGms                    0
w_bpSaved                  0
w_bpFaced                  0
l_ace                      0
l_df                       0
l_svpt                     0
l_1stIn                    0
l_1stWon                   0
l_2ndWon                   0
l_SvGms                    0
l_bpSaved                  0
l_bpFaced                  0
winner_rank              953
winner_rank_points       967
loser_rank              4268
loser_rank_points       4283
dtype: int64

In [16]:
data_atp[data_atp['loser_seed']=='A']

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
87927,Australian Open,Hard,128,G,20240115,NaN,Aziz Dougaz,L,188.0,26.8,A,Facundo Bagnis,L,183.0,33.8,7-6(4) 6-3,3,Q1,98.0,10.0,3.0,75.0,47.0,35.0,14.0,11.0,2.0,4.0,1.0,1.0,71.0,56.0,34.0,9.0,10.0,6.0,9.0,230.0,268.0,241.0,249.0

In [17]:
data_atp['loser_seed'].unique()

array([nan, 6.0, 5.0, 8.0, 7.0, 4.0, 2.0, 3.0, 1.0, 9.0, 25.0, 27.0, 21.0,
       16.0, 11.0, 15.0, 13.0, 17.0, 30.0, 26.0, 22.0, 28.0, 32.0, 20.0,
       23.0, 29.0, 31.0, 19.0, 18.0, 24.0, 12.0, 14.0, 10.0, 33.0, '7',
       '2', '3', '8', '12', '11', '10', '6', '5', '4', 'A', '18', 'WC',
       '25', '23', '15', '21', '16', '20', '19', '9', '32', '13', '17',
       '31', '27', '29', '22', '14', '1', '24', 'Q', 'LL', '30', '26',
       '28', '33'], dtype=object)

In [18]:
def transform_seed(value):
    """
    Transform values in the 'winner_seed' or 'loser_seed' columns.

    'Q', 'LL', and 'WC' remain unchanged.
    Numeric values are converted to 'S' (Seed).
    NaN and 'A' are converted to 'UN' (Unseed).

    :param value: str or NaN - Value from the 'winner_seed' or 'loser_seed' columns
    :return: str - Transformed value ('S', 'UN', 'WC', 'Q', 'LL', or original value)
    """
    if pd.isna(value) or value == 'A':
        return 'UN'
    elif value in ['WC', 'Q', 'LL']:
        return value
    else:
        try:
            float(value)
            return 'S'
        except ValueError:
            return value

data_atp['winner_seed'] = data_atp['winner_seed'].apply(transform_seed)
data_atp['winner_seed'].unique()

array(['UN', 'S', 'WC', 'LL', 'Q'], dtype=object)

In [19]:
data_atp['loser_seed'] = data_atp['loser_seed'].apply(transform_seed)
data_atp['loser_seed'].unique()

array(['UN', 'S', 'WC', 'Q', 'LL'], dtype=object)

In [20]:
data_atp.isnull().sum()

tourney_name              0
surface                   0
draw_size                 0
tourney_level             0
tourney_date              0
winner_seed               0
winner_name               0
winner_hand               7
winner_ht             16932
winner_age               24
loser_seed                0
loser_name                0
loser_hand               27
loser_ht              28560
loser_age               235
score                     0
best_of                   0
round                     0
minutes                5945
w_ace                     0
w_df                      0
w_svpt                    0
w_1stIn                   0
w_1stWon                  0
w_2ndWon                  0
w_SvGms                   0
w_bpSaved                 0
w_bpFaced                 0
l_ace                     0
l_df                      0
l_svpt                    0
l_1stIn                   0
l_1stWon                  0
l_2ndWon                  0
l_SvGms                   0
l_bpSaved                 0
l_bpFaced                 0
winner_rank             953
winner_rank_points      967
loser_rank             4268
loser_rank_points      4283
dtype: int64

In [21]:
data_atp.dtypes

tourney_name           object
surface                object
draw_size               int64
tourney_level          object
tourney_date            int64
winner_seed            object
winner_name            object
winner_hand            object
winner_ht             float64
winner_age            float64
loser_seed             object
loser_name             object
loser_hand             object
loser_ht              float64
loser_age             float64
score                  object
best_of                 int64
round                  object
minutes               float64
w_ace                 float64
w_df                  float64
w_svpt                float64
w_1stIn               float64
w_1stWon              float64
w_2ndWon              float64
w_SvGms               float64
w_bpSaved             float64
w_bpFaced             float64
l_ace                 float64
l_df                  float64
l_svpt                float64
l_1stIn               float64
l_1stWon              float64
l_2ndWon              float64
l_SvGms               float64
l_bpSaved             float64
l_bpFaced             float64
winner_rank           float64
winner_rank_points    float64
loser_rank            float64
loser_rank_points     float64
dtype: object

In [22]:
# Remove records where less than one set was played. In such cases, the 'score' column will not contain the numbers '6' or '7'.

# Create a mask for rows that contain the number '6' or '7' in the 'score' column
mask = data_atp['score'].str.contains(r'[67]', na=False)

# Filter the rows where 'score' contains either '6' or '7'
data_atp = data_atp[mask]

# Check the result and reset the index
data_atp.reset_index(drop=True, inplace=True)
data_atp.tail()

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
145456,Tour Finals,Hard,8,F,20181112,S,Novak Djokovic,R,188.0,31.4,S,Marin Cilic,R,198.0,30.1,7-6(7) 6-2,3,RR,95.0,3.0,0.0,53.0,31.0,28.0,20.0,10.0,0.0,0.0,8.0,2.0,77.0,44.0,35.0,15.0,10.0,6.0,8.0,1.0,8045.0,7.0,4050.0
145457,Tour Finals,Hard,8,F,20181112,S,Novak Djokovic,R,188.0,31.4,S,Alexander Zverev,R,198.0,21.5,6-4 6-1,3,RR,76.0,1.0,3.0,52.0,32.0,24.0,14.0,9.0,2.0,2.0,9.0,2.0,50.0,30.0,20.0,7.0,8.0,2.0,5.0,1.0,8045.0,5.0,5085.0
145458,Tour Finals,Hard,8,F,20181112,S,Alexander Zverev,R,198.0,21.5,S,Roger Federer,R,185.0,37.2,7-5 7-6(5),3,SF,95.0,7.0,1.0,65.0,43.0,38.0,14.0,12.0,2.0,3.0,3.0,0.0,65.0,37.0,29.0,17.0,12.0,0.0,2.0,5.0,5085.0,3.0,6020.0
145459,Tour Finals,Hard,8,F,20181112,S,Novak Djokovic,R,188.0,31.4,S,Kevin Anderson,R,203.0,32.4,6-2 6-2,3,SF,75.0,6.0,1.0,39.0,27.0,23.0,9.0,8.0,0.0,0.0,4.0,3.0,60.0,33.0,23.0,7.0,8.0,5.0,9.0,1.0,8045.0,6.0,4310.0
145460,Tour Finals,Hard,8,F,20181112,S,Alexander Zverev,R,198.0,21.5,S,Novak Djokovic,R,188.0,31.4,6-4 6-3,3,F,80.0,10.0,3.0,46.0,33.0,26.0,7.0,9.0,0.0,1.0,1.0,1.0,57.0,34.0,25.0,8.0,10.0,2.0,6.0,5.0,5085.0,1.0,8045.0

In [23]:
# As we see, in matches where 'w_svpt' == 0, there is no relevant data to be studied, as it was stored incorrectly. 
# We will exclude these records.

data_atp[(data_atp['w_svpt']==0) | (data_atp['l_svpt']==0)]

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
3681,Mons CH,Hard,32,C,20111003,UN,Yannick Mertens,R,188.0,24.2,UN,Josh Goodall,R,188.0,25.9,6-2 6-3,3,R32,59.0,4.0,0.0,47.0,24.0,20.0,15.0,9.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,233.0,216.0,340.0,130.0
3691,Mons CH,Hard,32,C,20111003,S,Steve Darcis,R,178.0,27.5,UN,Conor Niland,R,185.0,30.0,6-1 7-6(6),3,R32,88.0,2.0,0.0,53.0,30.0,22.0,16.0,9.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,89.0,615.0,203.0,261.0
3693,Mons CH,Hard,32,C,20111003,UN,Malek Jaziri,R,185.0,27.7,UN,Jonathan Dasnieres De Veigy,L,175.0,24.7,7-5 7-6(1),3,R32,120.0,4.0,3.0,107.0,63.0,45.0,22.0,12.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,146.0,391.0,234.0,215.0
3711,Sacramento CH,Hard,32,C,20111003,UN,Roman Borvanov,R,183.0,29.5,UN,Steve Johnson,R,188.0,21.7,3-6 6-4 6-3,3,R32,140.0,1.0,2.0,93.0,59.0,33.0,19.0,14.0,5.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,212.0,240.0,418.0,90.0
3719,Sacramento CH,Hard,32,C,20111003,UN,Denis Gremelmayr,L,183.0,30.1,UN,Jamie Baker,R,183.0,25.1,6-1 3-6 6-4,3,R32,118.0,4.0,2.0,85.0,54.0,37.0,14.0,13.0,10.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,163.0,318.0,273.0,180.0
4326,Knoxville CH,Hard,32,C,20111107,S,Uladzimir Ignatik,R,183.0,21.3,UN,Dimitar Kutrovsky,R,175.0,24.1,6-4 7-6(6),3,R32,81.0,16.0,1.0,64.0,39.0,33.0,17.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,171.0,289.0,522.0,58.0
5417,Geneva CH,Hard,32,C,20111107,UN,Michael Lammer,R,185.0,29.6,UN,Holger Fischer,R,NaN,30.9,6-3 6-3,3,R32,78.0,2.0,3.0,49.0,28.0,22.0,13.0,9.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,246.0,197.0,503.0,64.0
6833,Palermo CH,Clay,32,C,20111003,UN,Benoit Paire,R,196.0,22.4,UN,Javier Marti,R,NaN,19.7,6-3 7-6(5),3,R32,95.0,6.0,2.0,77.0,48.0,35.0,14.0,11.0,3.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,110.0,525.0,193.0,272.0
7243,Ortisei CH,Carpet,32,C,20111107,UN,Benjamin Becker,R,178.0,30.3,UN,Mateusz Kowalczyk,R,193.0,24.5,7-6(8) 3-6 6-4,3,R32,101.0,7.0,7.0,86.0,48.0,42.0,21.0,15.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,253.0,190.0,908.0,10.0
7252,Ortisei CH,Carpet,32,C,20111107,S,Adrian Ungur,R,178.0,26.7,UN,Mikhail Elgin,R,183.0,30.0,6-1 6-0,3,R32,42.0,8.0,1.0,32.0,16.0,14.0,14.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,116.0,497.0,581.0,41.0
8178,Buenos Aires CH,Clay,32,C,20111107,UN,Alessio Di Mauro,L,185.0,34.2,UN,Leandro Migani,R,NaN,26.6,6-7(3) 6-3 6-4,3,R32,169.0,5.0,5.0,110.0,62.0,43.0,23.0,15.0,10.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,224.0,225.0,516.0,60.0
21633,Blumenau CH,Clay,32,C,20120409,S,Gastao Elias,R,178.0,21.3,UN,Grzegorz Panfil,L,183.0,24.2,6-3 6-1,3,R32,52.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,222.0,222.0,414.0,93.0
75547,Beijing,Hard,32,A,20111003,UN,Ivan Ljubicic,R,193.0,32.5,UN,Teymuraz Gabashvili,R,188.0,26.3,7-5 7-5,3,R32,98.0,14.0,3.0,56.0,37.0,30.0,10.0,12.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,1375.0,128.0,432.0
75552,Beijing,Hard,32,A,20111003,UN,Albert Montanes,R,175.0,30.8,UN,Paul Capdeville,R,190.0,28.5,6-3 6-3,3,R32,53.0,12.0,1.0,47.0,25.0,24.0,13.0,9.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55.0,825.0,103.0,563.0

In [24]:
data_atp = data_atp.drop(data_atp[(data_atp['w_svpt']==0) | (data_atp['l_svpt']==0)].index)
data_atp.reset_index(drop=True, inplace=True)
data_atp.tail()

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
145442,Tour Finals,Hard,8,F,20181112,S,Novak Djokovic,R,188.0,31.4,S,Marin Cilic,R,198.0,30.1,7-6(7) 6-2,3,RR,95.0,3.0,0.0,53.0,31.0,28.0,20.0,10.0,0.0,0.0,8.0,2.0,77.0,44.0,35.0,15.0,10.0,6.0,8.0,1.0,8045.0,7.0,4050.0
145443,Tour Finals,Hard,8,F,20181112,S,Novak Djokovic,R,188.0,31.4,S,Alexander Zverev,R,198.0,21.5,6-4 6-1,3,RR,76.0,1.0,3.0,52.0,32.0,24.0,14.0,9.0,2.0,2.0,9.0,2.0,50.0,30.0,20.0,7.0,8.0,2.0,5.0,1.0,8045.0,5.0,5085.0
145444,Tour Finals,Hard,8,F,20181112,S,Alexander Zverev,R,198.0,21.5,S,Roger Federer,R,185.0,37.2,7-5 7-6(5),3,SF,95.0,7.0,1.0,65.0,43.0,38.0,14.0,12.0,2.0,3.0,3.0,0.0,65.0,37.0,29.0,17.0,12.0,0.0,2.0,5.0,5085.0,3.0,6020.0
145445,Tour Finals,Hard,8,F,20181112,S,Novak Djokovic,R,188.0,31.4,S,Kevin Anderson,R,203.0,32.4,6-2 6-2,3,SF,75.0,6.0,1.0,39.0,27.0,23.0,9.0,8.0,0.0,0.0,4.0,3.0,60.0,33.0,23.0,7.0,8.0,5.0,9.0,1.0,8045.0,6.0,4310.0
145446,Tour Finals,Hard,8,F,20181112,S,Alexander Zverev,R,198.0,21.5,S,Novak Djokovic,R,188.0,31.4,6-4 6-3,3,F,80.0,10.0,3.0,46.0,33.0,26.0,7.0,9.0,0.0,1.0,1.0,1.0,57.0,34.0,25.0,8.0,10.0,2.0,6.0,5.0,5085.0,1.0,8045.0

In [25]:
# Sort the dataframe by 'date', 'name', and 'round'

data_atp['round'].unique()

array(['R32', 'R16', 'QF', 'SF', 'F', 'R128', 'R64', 'RR', 'Q1', 'Q2',
       'Q3', 'BR'], dtype=object)

In [26]:
data_atp[data_atp['round']=='BR']

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
19726,Rio Olympics,Hard,64,A,20160808,S,Kei Nishikori,R,178.0,26.6,S,Rafael Nadal,L,185.0,30.1,6-2 6-7(1) 6-3,3,BR,169.0,7.0,2.0,89.0,52.0,36.0,24.0,15.0,3.0,5.0,5.0,1.0,106.0,82.0,49.0,11.0,14.0,8.0,13.0,7.0,4390.0,5.0,4940.0

In [27]:
# The 'BR' round stands for the Bronze medal match at the Olympics. 
# It is acceptable to replace 'BR' with 'F' (Final).

data_atp['round'] = data_atp['round'].replace('BR', 'F')
data_atp['round'].unique()

array(['R32', 'R16', 'QF', 'SF', 'F', 'R128', 'R64', 'RR', 'Q1', 'Q2',
       'Q3'], dtype=object)

In [28]:
# Create a round order for tournament rounds, from group stages to the final match
round_order = ['RR', 'Q1', 'Q2', 'Q3', 'R128', 'R64', 'R32', 'R16', 'QF', 'SF', 'F']

data_atp['round'] = pd.Categorical(data_atp['round'], categories=round_order, ordered=True)

In [29]:
data_atp.sort_values(by=['tourney_date', 'tourney_name', 'round'], inplace=True)
data_atp.reset_index(drop=True, inplace=True)
data_atp.tail(10)

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
145437,Skopje CH,Clay,32,C,20240520,UN,Gerard Campana Lee,U,NaN,19.6,UN,Giovanni Fonio,U,NaN,26.0,6-1 6-2,3,R16,69.0,2.0,2.0,44.0,24.0,16.0,15.0,8.0,3.0,4.0,1.0,3.0,37.0,19.0,10.0,4.0,7.0,0.0,5.0,349.0,144.0,302.0,179.0
145438,Skopje CH,Clay,32,C,20240520,UN,Andrew Paulson,U,NaN,22.5,UN,Mirza Basic,R,188.0,32.8,6-4 6-3,3,R16,85.0,2.0,6.0,59.0,34.0,27.0,14.0,9.0,4.0,4.0,4.0,2.0,61.0,38.0,24.0,12.0,10.0,9.0,12.0,328.0,158.0,725.0,37.0
145439,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,S,Ergi Kirkin,R,180.0,25.3,6-2 6-1,3,R16,58.0,1.0,0.0,34.0,23.0,19.0,9.0,7.0,0.0,0.0,2.0,2.0,49.0,29.0,19.0,4.0,8.0,3.0,8.0,664.0,48.0,258.0,224.0
145440,Skopje CH,Clay,32,C,20240520,UN,Kamil Majchrzak,R,183.0,28.3,UN,Alexander Weis,U,NaN,27.0,6-3 7-6(5),3,QF,108.0,2.0,1.0,66.0,41.0,37.0,13.0,11.0,3.0,3.0,3.0,0.0,81.0,53.0,33.0,18.0,10.0,6.0,7.0,351.0,143.0,303.0,176.0
145441,Skopje CH,Clay,32,C,20240520,UN,Ryan Seggerman,U,NaN,24.7,UN,Neil Oberleitner,R,NaN,24.7,2-6 7-6(5) 7-6(6),3,QF,137.0,16.0,5.0,107.0,66.0,44.0,25.0,16.0,4.0,7.0,9.0,7.0,109.0,66.0,53.0,20.0,16.0,4.0,5.0,555.0,67.0,636.0,53.0
145442,Skopje CH,Clay,32,C,20240520,UN,Gerard Campana Lee,U,NaN,19.6,UN,Marco Cecchinato,R,185.0,31.6,6-4 6-2,3,QF,100.0,0.0,4.0,49.0,33.0,26.0,11.0,9.0,0.0,0.0,0.0,7.0,68.0,30.0,22.0,17.0,9.0,9.0,12.0,349.0,144.0,387.0,124.0
145443,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Andrew Paulson,U,NaN,22.5,3-6 6-4 6-4,3,QF,154.0,5.0,8.0,108.0,56.0,40.0,26.0,15.0,11.0,14.0,8.0,8.0,111.0,60.0,45.0,24.0,14.0,8.0,11.0,664.0,48.0,328.0,158.0
145444,Skopje CH,Clay,32,C,20240520,UN,Kamil Majchrzak,R,183.0,28.3,UN,Ryan Seggerman,U,NaN,24.7,7-6(2) 6-7(6) 6-2,3,SF,135.0,6.0,0.0,101.0,60.0,45.0,26.0,16.0,3.0,5.0,5.0,5.0,99.0,58.0,40.0,22.0,16.0,4.0,8.0,351.0,143.0,555.0,67.0
145445,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Gerard Campana Lee,U,NaN,19.6,6-7(4) 6-3 6-2,3,SF,184.0,3.0,4.0,104.0,60.0,44.0,22.0,15.0,2.0,4.0,3.0,6.0,106.0,65.0,39.0,19.0,14.0,7.0,12.0,664.0,48.0,349.0,144.0
145446,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Kamil Majchrzak,R,183.0,28.3,6-3 6-3,3,F,81.0,3.0,0.0,49.0,27.0,18.0,15.0,9.0,1.0,2.0,5.0,1.0,63.0,37.0,23.0,11.0,9.0,6.0,10.0,664.0,48.0,351.0,143.0

### WORKING WITH THE "score" COLUMN

In [30]:
# Use a regular expression to find letters (without digits and symbols)
# The pattern [a-zA-Z] matches any letter of the alphabet (both uppercase and lowercase)
mask = data_atp['score'].str.contains(r'[a-zA-Z]')

# Select all rows where the 'score' column contains letters
records_with_letters = data_atp[mask]

records_with_letters.tail(3)

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
145389,Lyon,Clay,32,A,20240520,S,Tomas Martin Etcheverry,R,196.0,24.8,UN,Thiago Seyboth Wild,R,185.0,24.1,7-5 3-0 RET,3,R16,100.0,3.0,1.0,55.0,39.0,29.0,6.0,8.0,6.0,7.0,0.0,2.0,52.0,33.0,18.0,8.0,7.0,5.0,8.0,29.0,1410.0,58.0,837.0
145423,Skopje CH,Clay,32,C,20240520,S,Maks Kasnikowski,U,NaN,20.8,UN,Orlando Luz,R,180.0,26.2,6-7(5) 7-6(9) 4-2 RET,3,R32,190.0,4.0,7.0,120.0,65.0,53.0,27.0,15.0,7.0,8.0,8.0,11.0,113.0,60.0,50.0,24.0,15.0,4.0,6.0,265.0,218.0,352.0,143.0
145430,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Sergey Fomin,R,NaN,23.2,5-7 7-5 3-0 RET,3,R32,151.0,9.0,6.0,78.0,45.0,32.0,18.0,13.0,3.0,6.0,4.0,7.0,121.0,82.0,47.0,19.0,14.0,14.0,19.0,664.0,48.0,654.0,51.0

In [31]:
def extract_letters(value):
    """
    Extract words (letters) from a string.

    :param value: str or any - The value from the 'score' column in the dataframe.
    :return: list - A list of letter sequences found in the 'value'.
    """
    return re.findall(r'[a-zA-Z]+', str(value)) 

# Apply the function to the 'score' column and concatenate all results into one list
letters_in_scores = data_atp['score'].apply(extract_letters).sum()

# Get the unique letter marks from the concatenated list
unique_letters = pd.Series(letters_in_scores).unique()

unique_letters

array(['RET', 'DEF', 'Def'], dtype=object)

In [32]:
data_atp['score'].tolist()[:10]

['6-1 6-0',
 '6-4 6-2',
 '7-6(6) 7-6(6)',
 '4-6 7-5 7-6(2)',
 '6-0 6-4',
 '7-5 6-2',
 '6-7(4) 7-5 6-4',
 '6-0 6-3',
 '6-3 6-4',
 '6-2 6-2']

In [33]:
# Функція для видалення чисел у дужках
def remove_bracketed_numbers(score):
    """
    Remove numbers inside parentheses.

    :param score: str - The match score as a string, potentially containing numbers inside parentheses.
    :return: str - The score string with any numbers inside parentheses removed.
    """
    return re.sub(r'\(\d+\)', '', score)

# Apply the function to the 'score' column to remove bracketed numbers from all scores
data_atp['score'] = data_atp['score'].apply(remove_bracketed_numbers)

data_atp['score'].tolist()[:10]

['6-1 6-0',
 '6-4 6-2',
 '7-6 7-6',
 '4-6 7-5 7-6',
 '6-0 6-4',
 '7-5 6-2',
 '6-7 7-5 6-4',
 '6-0 6-3',
 '6-3 6-4',
 '6-2 6-2']

In [34]:
# Функція для обчислення кількості геймів і тайбрейків
def calculate_games(score):
    """
    Calculate the number of games and tiebreaks from a score string

    :param score: str - The match score string, e.g., '6-3 7-5 6-7 6-4'.
    :return: pd.Series - A series with the following values:
             - w_games: Total games won by the winner
             - l_games: Total games won by the loser
             - total_games: Total number of games in the match
             - p1_tiebreaks_w: Number of tiebreaks won by the winner
             - p2_tiebreaks_w: Number of tiebreaks won by the loser
             - tiebreaks: Total number of tiebreaks in the match
    """
    # Split the score into sets and each set into won/lost games
    sets = re.findall(r'\d+-\d+', score)
    
    w_games = 0
    l_games = 0
    w_tiebreaks_w = 0
    l_tiebreaks_w = 0

    for set_score in sets:
        # Split the score for each set into winner's and loser's games
        w_set, l_set = map(int, set_score.split('-'))

        # Add the number of games won by each player
        w_games += w_set
        l_games += l_set

        # Check for tiebreaks (7-6 or 6-7 score)
        if (w_set == 7 and l_set == 6):
            w_tiebreaks_w += 1
        if (w_set == 6 and l_set == 7):
            l_tiebreaks_w += 1

    # Calculate the total number of tiebreaks
    tiebreaks = w_tiebreaks_w + l_tiebreaks_w
    total_games = w_games + l_games

    return pd.Series([w_games, l_games, total_games, w_tiebreaks_w, l_tiebreaks_w, tiebreaks])

# Apply the function to each row in the 'score' column
data_atp[['w_games', 'l_games', 'total_games', 'p1_tiebreaks_w', 'p2_tiebreaks_w', 'tiebreaks']] = data_atp['score'].apply(calculate_games)

In [35]:
data_atp.tail()

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,w_games,l_games,total_games,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks
145442,Skopje CH,Clay,32,C,20240520,UN,Gerard Campana Lee,U,NaN,19.6,UN,Marco Cecchinato,R,185.0,31.6,6-4 6-2,3,QF,100.0,0.0,4.0,49.0,33.0,26.0,11.0,9.0,0.0,0.0,0.0,7.0,68.0,30.0,22.0,17.0,9.0,9.0,12.0,349.0,144.0,387.0,124.0,12,6,18,0,0,0
145443,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Andrew Paulson,U,NaN,22.5,3-6 6-4 6-4,3,QF,154.0,5.0,8.0,108.0,56.0,40.0,26.0,15.0,11.0,14.0,8.0,8.0,111.0,60.0,45.0,24.0,14.0,8.0,11.0,664.0,48.0,328.0,158.0,15,14,29,0,0,0
145444,Skopje CH,Clay,32,C,20240520,UN,Kamil Majchrzak,R,183.0,28.3,UN,Ryan Seggerman,U,NaN,24.7,7-6 6-7 6-2,3,SF,135.0,6.0,0.0,101.0,60.0,45.0,26.0,16.0,3.0,5.0,5.0,5.0,99.0,58.0,40.0,22.0,16.0,4.0,8.0,351.0,143.0,555.0,67.0,19,15,34,1,1,2
145445,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Gerard Campana Lee,U,NaN,19.6,6-7 6-3 6-2,3,SF,184.0,3.0,4.0,104.0,60.0,44.0,22.0,15.0,2.0,4.0,3.0,6.0,106.0,65.0,39.0,19.0,14.0,7.0,12.0,664.0,48.0,349.0,144.0,18,12,30,0,1,1
145446,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Kamil Majchrzak,R,183.0,28.3,6-3 6-3,3,F,81.0,3.0,0.0,49.0,27.0,18.0,15.0,9.0,1.0,2.0,5.0,1.0,63.0,37.0,23.0,11.0,9.0,6.0,10.0,664.0,48.0,351.0,143.0,12,6,18,0,0,0

In [36]:
# Check records with inappropriate statistics where the total number of games is less than the sum of 
# the service games played by both players, minus the number of tiebreaks.

len(data_atp[(data_atp['w_SvGms']+data_atp['l_SvGms']) < (data_atp['total_games']-data_atp['tiebreaks'])])

545

In [37]:
data_atp[(data_atp['w_SvGms']+data_atp['l_SvGms']) < (data_atp['total_games']-data_atp['tiebreaks'])].tail()

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,w_games,l_games,total_games,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks
136078,Us Open,Hard,128,G,20230828,S,Nicolas Moreno De Alboran,R,185.0,26.1,UN,Joris De Loore,R,191.0,30.3,3-6 7-6 7-6,3,Q3,187.0,7.0,7.0,117.0,84.0,65.0,17.0,0.0,4.0,5.0,17.0,4.0,102.0,57.0,49.0,30.0,0.0,0.0,0.0,131.0,470.0,173.0,353.0,17,18,35,2,0,2
136079,Us Open,Hard,128,G,20230828,UN,Yu Hsiou Hsu,R,178.0,24.4,UN,Aidan Mayo,R,183.0,20.2,7-5 6-3,3,Q3,86.0,2.0,4.0,64.0,40.0,35.0,11.0,0.0,1.0,1.0,7.0,5.0,60.0,27.0,22.0,15.0,0.0,1.0,3.0,237.0,268.0,462.0,96.0,13,8,21,0,0,0
136080,Us Open,Hard,128,G,20230828,S,Dominic Stricker,L,183.0,21.0,UN,Thiago Agustin Tirante,R,185.0,22.3,6-2 6-3,3,Q3,83.0,5.0,4.0,50.0,28.0,26.0,12.0,0.0,3.0,3.0,4.0,2.0,63.0,37.0,27.0,9.0,0.0,9.0,12.0,128.0,480.0,150.0,408.0,12,5,17,0,0,0
136081,Us Open,Hard,128,G,20230828,UN,Emilio Nava,R,185.0,21.7,UN,Eliot Spizzirri,R,183.0,21.6,6-3 3-6 3-1 RET,3,Q3,102.0,9.0,5.0,68.0,45.0,29.0,12.0,0.0,2.0,5.0,3.0,1.0,69.0,39.0,26.0,11.0,0.0,3.0,7.0,154.0,402.0,1137.0,7.0,12,10,22,0,0,0
136086,Us Open,Hard,128,G,20230828,UN,Arthur Fils,R,185.0,19.2,S,Tallon Griekspoor,R,188.0,27.1,4-6 6-3 5-7 6-4 7-5,5,R128,238.0,22.0,6.0,169.0,111.0,86.0,24.0,27.0,11.0,15.0,13.0,8.0,155.0,90.0,70.0,29.0,25.0,6.0,11.0,48.0,1007.0,24.0,1446.0,28,25,53,0,0,0

In [38]:
# In these records, there is missing or incorrect data in the columns 'w_SvGms' or 'l_SvGms'. We will delete those records.

data_atp = data_atp.drop(data_atp[(data_atp['w_SvGms']+data_atp['l_SvGms']) < (data_atp['total_games']-data_atp['tiebreaks'])].index)
data_atp.reset_index(drop=True, inplace=True)
data_atp.tail()

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,w_games,l_games,total_games,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks
144897,Skopje CH,Clay,32,C,20240520,UN,Gerard Campana Lee,U,NaN,19.6,UN,Marco Cecchinato,R,185.0,31.6,6-4 6-2,3,QF,100.0,0.0,4.0,49.0,33.0,26.0,11.0,9.0,0.0,0.0,0.0,7.0,68.0,30.0,22.0,17.0,9.0,9.0,12.0,349.0,144.0,387.0,124.0,12,6,18,0,0,0
144898,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Andrew Paulson,U,NaN,22.5,3-6 6-4 6-4,3,QF,154.0,5.0,8.0,108.0,56.0,40.0,26.0,15.0,11.0,14.0,8.0,8.0,111.0,60.0,45.0,24.0,14.0,8.0,11.0,664.0,48.0,328.0,158.0,15,14,29,0,0,0
144899,Skopje CH,Clay,32,C,20240520,UN,Kamil Majchrzak,R,183.0,28.3,UN,Ryan Seggerman,U,NaN,24.7,7-6 6-7 6-2,3,SF,135.0,6.0,0.0,101.0,60.0,45.0,26.0,16.0,3.0,5.0,5.0,5.0,99.0,58.0,40.0,22.0,16.0,4.0,8.0,351.0,143.0,555.0,67.0,19,15,34,1,1,2
144900,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Gerard Campana Lee,U,NaN,19.6,6-7 6-3 6-2,3,SF,184.0,3.0,4.0,104.0,60.0,44.0,22.0,15.0,2.0,4.0,3.0,6.0,106.0,65.0,39.0,19.0,14.0,7.0,12.0,664.0,48.0,349.0,144.0,18,12,30,0,1,1
144901,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Kamil Majchrzak,R,183.0,28.3,6-3 6-3,3,F,81.0,3.0,0.0,49.0,27.0,18.0,15.0,9.0,1.0,2.0,5.0,1.0,63.0,37.0,23.0,11.0,9.0,6.0,10.0,664.0,48.0,351.0,143.0,12,6,18,0,0,0

### Create new statistical variables

#### All values measured between 0 and 1 (percentage)

#### s for serve; r for receive

#### winner is p1; loser is p2

#### .
#### .
#### .




#### p1_1st_in  - player1 1st serve in

#### p1_1st_ptwon - player1 1st serve points won

#### p1_2nd_ptwon - player1 2nd serve points won

#### p1_bp_saved - player1 break points saved, 1 if there were no bp faced

#### p1_ace_per_s - player1 aces per serve

#### p1_df_per_s - player1 double faults per serve

#### p1_1st_r_ptwon - player1 1st serve points won on receive

#### p1_2nd_r_ptwon - player1 2nd serve points won on receive

#### p1_bp_won - player1 break points won

#### p1_tot_pt_won_s - player1 total points won on serve

#### p1_tot_pt_won_r - player1 total points won on receive

#### p1_tot_pt_won - player1 total points won 

#### p1_gms_won_s - player1 games won on serve

#### p1_gms_won_r - player1 games won on receive

#### p1_tot_gms_won - player1 total games won

In [39]:
data_atp['p1_1st_in'] = round(data_atp['w_1stIn'] / data_atp['w_svpt'], 2)
data_atp['p1_1st_ptwon'] = round(data_atp['w_1stWon'] / data_atp['w_1stIn'], 2)
data_atp['p1_2nd_ptwon'] = np.where(data_atp['w_2ndWon'] == 0, 0, round(data_atp['w_2ndWon'] / (data_atp['w_svpt'] - data_atp['w_1stIn']), 2))
data_atp['p1_bp_saved'] = np.where(data_atp['w_bpFaced'] == 0, 1.0, round(data_atp['w_bpSaved'] / data_atp['w_bpFaced'], 2))
data_atp['p1_ace_per_s'] = round(data_atp['w_ace'] / data_atp['w_svpt'], 2)
data_atp['p1_df_per_s'] = round(data_atp['w_df'] / data_atp['w_svpt'], 2)
data_atp['p1_1st_r_ptwon'] = round((data_atp['l_1stIn'] - data_atp['l_1stWon']) / data_atp['l_1stIn'], 2)
data_atp['p1_2nd_r_ptwon'] = np.where((data_atp['l_svpt'] - data_atp['l_1stIn'] - data_atp['l_2ndWon']) == 0, 0, round((data_atp['l_svpt'] - data_atp['l_1stIn'] - data_atp['l_2ndWon']) / (data_atp['l_svpt'] - data_atp['l_1stIn']), 2))
data_atp['p1_bp_won'] = np.where(data_atp['l_bpFaced'] == 0, 0.0, round((data_atp['l_bpFaced'] - data_atp['l_bpSaved']) / data_atp['l_bpFaced'], 2))
data_atp['p1_tot_pt_won_s'] = round((data_atp['w_1stWon'] + data_atp['w_2ndWon']) / data_atp['w_svpt'], 2)
data_atp['p1_tot_pt_won_r'] = round((data_atp['l_svpt'] - data_atp['l_1stWon'] - data_atp['l_2ndWon']) / data_atp['l_svpt'], 2)
data_atp['p1_tot_pt_won'] = round((data_atp['w_1stWon'] + data_atp['w_2ndWon'] + (data_atp['l_svpt'] - data_atp['l_1stWon'] - data_atp['l_2ndWon'])) / (data_atp['w_svpt'] + data_atp['l_svpt']), 2)
data_atp['p1_gms_won_s'] = round((data_atp['w_SvGms'] - (data_atp['w_bpFaced'] - data_atp['w_bpSaved'])) / data_atp['w_SvGms'], 2)
data_atp['p1_gms_won_r'] = round((data_atp['l_bpFaced'] - data_atp['l_bpSaved']) /  data_atp['l_SvGms'], 2)
data_atp['p1_tot_gms_won'] = round(data_atp['w_games'] / data_atp['total_games'], 2)

data_atp['p2_1st_in'] = round(data_atp['l_1stIn'] / data_atp['l_svpt'], 2)
data_atp['p2_1st_ptwon'] = round(data_atp['l_1stWon'] / data_atp['l_1stIn'], 2)
data_atp['p2_2nd_ptwon'] = np.where(data_atp['l_2ndWon'] == 0, 0, round(data_atp['l_2ndWon'] / (data_atp['l_svpt'] - data_atp['l_1stIn']), 2))
data_atp['p2_bp_saved'] = np.where(data_atp['l_bpFaced'] == 0, 1.0, round(data_atp['l_bpSaved'] / data_atp['l_bpFaced'], 2))
data_atp['p2_ace_per_s'] = round(data_atp['l_ace'] / data_atp['l_svpt'], 2)
data_atp['p2_df_per_s'] = round(data_atp['l_df'] / data_atp['l_svpt'], 2)
data_atp['p2_1st_r_ptwon'] = round((data_atp['w_1stIn'] - data_atp['w_1stWon']) / data_atp['w_1stIn'], 2)
data_atp['p2_2nd_r_ptwon'] = np.where((data_atp['w_svpt'] - data_atp['w_1stIn'] - data_atp['w_2ndWon']) == 0, 0, round((data_atp['w_svpt'] - data_atp['w_1stIn'] - data_atp['w_2ndWon']) / (data_atp['w_svpt'] - data_atp['w_1stIn']), 2))
data_atp['p2_bp_won'] = np.where(data_atp['w_bpFaced'] == 0, 0.0, round((data_atp['w_bpFaced'] - data_atp['w_bpSaved']) / data_atp['w_bpFaced'], 2))
data_atp['p2_tot_pt_won_s'] = round((data_atp['l_1stWon'] + data_atp['l_2ndWon']) / data_atp['l_svpt'], 2)
data_atp['p2_tot_pt_won_r'] = round((data_atp['w_svpt'] - data_atp['w_1stWon'] - data_atp['w_2ndWon']) / data_atp['w_svpt'], 2)
data_atp['p2_tot_pt_won'] = round((data_atp['l_1stWon'] + data_atp['l_2ndWon'] + (data_atp['w_svpt'] - data_atp['w_1stWon'] - data_atp['w_2ndWon'])) / (data_atp['l_svpt'] + data_atp['w_svpt']), 2)
data_atp['p2_gms_won_s'] = round((data_atp['l_SvGms'] - (data_atp['l_bpFaced'] - data_atp['l_bpSaved'])) / data_atp['l_SvGms'], 2)
data_atp['p2_gms_won_r'] = round((data_atp['w_bpFaced'] - data_atp['w_bpSaved']) /  data_atp['w_SvGms'], 2)
data_atp['p2_tot_gms_won'] = round(data_atp['l_games'] / data_atp['total_games'], 2)

In [40]:
data_atp.isnull().sum()

tourney_name              0
surface                   0
draw_size                 0
tourney_level             0
tourney_date              0
winner_seed               0
winner_name               0
winner_hand               7
winner_ht             16779
winner_age               24
loser_seed                0
loser_name                0
loser_hand               27
loser_ht              28376
loser_age               234
score                     0
best_of                   0
round                     0
minutes                5891
w_ace                     0
w_df                      0
w_svpt                    0
w_1stIn                   0
w_1stWon                  0
w_2ndWon                  0
w_SvGms                   0
w_bpSaved                 0
w_bpFaced                 0
l_ace                     0
l_df                      0
l_svpt                    0
l_1stIn                   0
l_1stWon                  0
l_2ndWon                  0
l_SvGms                   0
l_bpSaved                 0
l_bpFaced                 0
winner_rank             937
winner_rank_points      951
loser_rank             4251
loser_rank_points      4266
w_games                   0
l_games                   0
total_games               0
p1_tiebreaks_w            0
p2_tiebreaks_w            0
tiebreaks                 0
p1_1st_in                 0
p1_1st_ptwon              0
p1_2nd_ptwon              0
p1_bp_saved               0
p1_ace_per_s              0
p1_df_per_s               0
p1_1st_r_ptwon            0
p1_2nd_r_ptwon            0
p1_bp_won                 0
p1_tot_pt_won_s           0
p1_tot_pt_won_r           0
p1_tot_pt_won             0
p1_gms_won_s              0
p1_gms_won_r              0
p1_tot_gms_won            0
p2_1st_in                 0
p2_1st_ptwon              0
p2_2nd_ptwon              0
p2_bp_saved               0
p2_ace_per_s              0
p2_df_per_s               0
p2_1st_r_ptwon            0
p2_2nd_r_ptwon            0
p2_bp_won                 0
p2_tot_pt_won_s           0
p2_tot_pt_won_r           0
p2_tot_pt_won             0
p2_gms_won_s              0
p2_gms_won_r              0
p2_tot_gms_won            0
dtype: int64

In [41]:
# Check for infinite values (inf) in the selected columns and count them
df = data_atp.select_dtypes((int, float))

count = np.isinf(df).values.sum()
count.item()

0

In [42]:
data_atp.head(3)

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_seed,winner_name,winner_hand,winner_ht,winner_age,loser_seed,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,w_games,l_games,total_games,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p2_1st_in,p2_1st_ptwon,p2_2nd_ptwon,p2_bp_saved,p2_ace_per_s,p2_df_per_s,p2_1st_r_ptwon,p2_2nd_r_ptwon,p2_bp_won,p2_tot_pt_won_s,p2_tot_pt_won_r,p2_tot_pt_won,p2_gms_won_s,p2_gms_won_r,p2_tot_gms_won
0,Brisbane,Hard,32,A,20100103,UN,Matheson Klein,U,NaN,20.4,UN,Mark Richards,R,NaN,16.0,6-1 6-0,3,Q1,72.0,6.0,4.0,47.0,27.0,19.0,10.0,6.0,3.0,4.0,1.0,4.0,48.0,21.0,11.0,4.0,7.0,3.0,10.0,855.0,13.0,NaN,NaN,12,1,13,0,0,0,0.57,0.70,0.50,0.75,0.13,0.09,0.48,0.85,0.70,0.62,0.69,0.65,0.83,1.00,0.92,0.44,0.52,0.15,0.30,0.02,0.08,0.30,0.50,0.25,0.31,0.38,0.35,0.00,0.17,0.08
1,Brisbane,Hard,32,A,20100103,UN,Joel Lindner,L,NaN,20.9,UN,Benjamin Mitchell,R,183.0,17.0,6-4 6-2,3,Q1,50.0,9.0,1.0,42.0,30.0,27.0,9.0,9.0,0.0,0.0,3.0,3.0,56.0,34.0,24.0,9.0,9.0,3.0,6.0,837.0,14.0,1068.0,6.0,12,6,18,0,0,0,0.71,0.90,0.75,1.00,0.21,0.02,0.29,0.59,0.50,0.86,0.41,0.60,1.00,0.33,0.67,0.61,0.71,0.41,0.50,0.05,0.05,0.10,0.25,0.00,0.59,0.14,0.40,0.67,0.00,0.33
2,Brisbane,Hard,32,A,20100103,S,Nick Lindahl,R,183.0,21.4,UN,Tobias Kamke,R,180.0,23.6,7-6 7-6,3,Q1,120.0,4.0,3.0,87.0,67.0,48.0,11.0,12.0,5.0,7.0,2.0,1.0,99.0,76.0,47.0,14.0,12.0,9.0,11.0,251.0,179.0,254.0,176.0,14,12,26,2,0,2,0.77,0.72,0.55,0.71,0.05,0.03,0.38,0.39,0.18,0.68,0.38,0.52,0.83,0.17,0.54,0.77,0.62,0.61,0.82,0.02,0.01,0.28,0.45,0.29,0.62,0.32,0.48,0.83,0.17,0.46

In [43]:
data_atp.shape

(144902, 77)

# Create a target variable

#### 1 if the first player (p1) is the winner, and 0 if the first player (p1) is the loser.

#### Duplicate dataset and swap positions. That means that we are going to have records about each match twice:

#### p1(winner)-p2(loser) (target 1)

#### p1(loser)-p2(winner) (taret 0)

In [44]:
# Rename columns to reflect players' roles: 'winner' -> 'p1' (first player), 'loser' -> 'p2' (second player) 
data_atp.rename(columns = {'winner_seed': 'p1_seed', 'winner_name': 'p1_name', 'winner_hand': 'p1_hand',
                       'winner_ht': 'p1_ht', 'winner_age': 'p1_age', 'loser_seed': 'p2_seed', 
                       'loser_name': 'p2_name', 'loser_hand': 'p2_hand', 'loser_ht': 'p2_ht', 
                       'loser_age': 'p2_age', 'winner_rank': 'p1_rank', 
                       'winner_rank_points': 'p1_rank_points', 'loser_rank': 'p2_rank',
                       'loser_rank_points': 'p2_rank_points'}, inplace=True)
data_atp.tail(3)

,tourney_name,surface,draw_size,tourney_level,tourney_date,p1_seed,p1_name,p1_hand,p1_ht,p1_age,p2_seed,p2_name,p2_hand,p2_ht,p2_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,p1_rank,p1_rank_points,p2_rank,p2_rank_points,w_games,l_games,total_games,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p2_1st_in,p2_1st_ptwon,p2_2nd_ptwon,p2_bp_saved,p2_ace_per_s,p2_df_per_s,p2_1st_r_ptwon,p2_2nd_r_ptwon,p2_bp_won,p2_tot_pt_won_s,p2_tot_pt_won_r,p2_tot_pt_won,p2_gms_won_s,p2_gms_won_r,p2_tot_gms_won
144899,Skopje CH,Clay,32,C,20240520,UN,Kamil Majchrzak,R,183.0,28.3,UN,Ryan Seggerman,U,NaN,24.7,7-6 6-7 6-2,3,SF,135.0,6.0,0.0,101.0,60.0,45.0,26.0,16.0,3.0,5.0,5.0,5.0,99.0,58.0,40.0,22.0,16.0,4.0,8.0,351.0,143.0,555.0,67.0,19,15,34,1,1,2,0.59,0.75,0.63,0.6,0.06,0.00,0.31,0.46,0.50,0.70,0.37,0.54,0.88,0.25,0.56,0.59,0.69,0.54,0.50,0.05,0.05,0.25,0.37,0.4,0.63,0.30,0.46,0.75,0.12,0.44
144900,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Gerard Campana Lee,U,NaN,19.6,6-7 6-3 6-2,3,SF,184.0,3.0,4.0,104.0,60.0,44.0,22.0,15.0,2.0,4.0,3.0,6.0,106.0,65.0,39.0,19.0,14.0,7.0,12.0,664.0,48.0,349.0,144.0,18,12,30,0,1,1,0.58,0.73,0.50,0.5,0.03,0.04,0.40,0.54,0.42,0.63,0.45,0.54,0.87,0.36,0.60,0.61,0.60,0.46,0.58,0.03,0.06,0.27,0.50,0.5,0.55,0.37,0.46,0.64,0.13,0.40
144901,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Kamil Majchrzak,R,183.0,28.3,6-3 6-3,3,F,81.0,3.0,0.0,49.0,27.0,18.0,15.0,9.0,1.0,2.0,5.0,1.0,63.0,37.0,23.0,11.0,9.0,6.0,10.0,664.0,48.0,351.0,143.0,12,6,18,0,0,0,0.55,0.67,0.68,0.5,0.06,0.00,0.38,0.58,0.40,0.67,0.46,0.55,0.89,0.44,0.67,0.59,0.62,0.42,0.60,0.08,0.02,0.33,0.32,0.5,0.54,0.33,0.45,0.56,0.11,0.33

In [45]:
# Drop columns that are no longer needed
data_atp.drop(['w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 
           'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 
           'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
           'score', 'w_games', 'l_games', 'total_games'], axis=1, inplace=True)

data_atp.tail(3)

,tourney_name,surface,draw_size,tourney_level,tourney_date,p1_seed,p1_name,p1_hand,p1_ht,p1_age,p2_seed,p2_name,p2_hand,p2_ht,p2_age,best_of,round,minutes,p1_rank,p1_rank_points,p2_rank,p2_rank_points,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p2_1st_in,p2_1st_ptwon,p2_2nd_ptwon,p2_bp_saved,p2_ace_per_s,p2_df_per_s,p2_1st_r_ptwon,p2_2nd_r_ptwon,p2_bp_won,p2_tot_pt_won_s,p2_tot_pt_won_r,p2_tot_pt_won,p2_gms_won_s,p2_gms_won_r,p2_tot_gms_won
144899,Skopje CH,Clay,32,C,20240520,UN,Kamil Majchrzak,R,183.0,28.3,UN,Ryan Seggerman,U,NaN,24.7,3,SF,135.0,351.0,143.0,555.0,67.0,1,1,2,0.59,0.75,0.63,0.6,0.06,0.00,0.31,0.46,0.50,0.70,0.37,0.54,0.88,0.25,0.56,0.59,0.69,0.54,0.50,0.05,0.05,0.25,0.37,0.4,0.63,0.30,0.46,0.75,0.12,0.44
144900,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Gerard Campana Lee,U,NaN,19.6,3,SF,184.0,664.0,48.0,349.0,144.0,0,1,1,0.58,0.73,0.50,0.5,0.03,0.04,0.40,0.54,0.42,0.63,0.45,0.54,0.87,0.36,0.60,0.61,0.60,0.46,0.58,0.03,0.06,0.27,0.50,0.5,0.55,0.37,0.46,0.64,0.13,0.40
144901,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Kamil Majchrzak,R,183.0,28.3,3,F,81.0,664.0,48.0,351.0,143.0,0,0,0,0.55,0.67,0.68,0.5,0.06,0.00,0.38,0.58,0.40,0.67,0.46,0.55,0.89,0.44,0.67,0.59,0.62,0.42,0.60,0.08,0.02,0.33,0.32,0.5,0.54,0.33,0.45,0.56,0.11,0.33

In [46]:
# Duplicate the dataset
atp_win = data_atp.copy()
atp_los = data_atp.copy()

atp_win.shape, atp_los.shape

((144902, 55), (144902, 55))

In [47]:
# Swap columns for losers (atp_los)
p1_lst = ['p1_seed', 'p1_name', 'p1_hand', 'p1_ht', 'p1_age', 'p1_rank', 'p1_rank_points', 
          'p1_tiebreaks_w', 'p1_1st_in', 'p1_1st_ptwon', 'p1_2nd_ptwon', 'p1_bp_saved', 
          'p1_ace_per_s', 'p1_df_per_s', 'p1_1st_r_ptwon', 'p1_2nd_r_ptwon', 'p1_bp_won', 
          'p1_tot_pt_won_s', 'p1_tot_pt_won_r', 'p1_tot_pt_won', 'p1_gms_won_s', 'p1_gms_won_r', 
          'p1_tot_gms_won']

p2_lst = ['p2_seed', 'p2_name', 'p2_hand', 'p2_ht', 'p2_age', 'p2_rank', 'p2_rank_points', 
          'p2_tiebreaks_w', 'p2_1st_in', 'p2_1st_ptwon', 'p2_2nd_ptwon', 'p2_bp_saved', 
          'p2_ace_per_s', 'p2_df_per_s', 'p2_1st_r_ptwon', 'p2_2nd_r_ptwon', 'p2_bp_won', 
          'p2_tot_pt_won_s', 'p2_tot_pt_won_r', 'p2_tot_pt_won', 'p2_gms_won_s', 'p2_gms_won_r', 
          'p2_tot_gms_won']

In [48]:
for i, j in zip(p1_lst, p2_lst):
    atp_los.loc[:,[i, j]] = atp_los.loc[:,[j, i]].values
    
atp_los.tail(3)

,tourney_name,surface,draw_size,tourney_level,tourney_date,p1_seed,p1_name,p1_hand,p1_ht,p1_age,p2_seed,p2_name,p2_hand,p2_ht,p2_age,best_of,round,minutes,p1_rank,p1_rank_points,p2_rank,p2_rank_points,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p2_1st_in,p2_1st_ptwon,p2_2nd_ptwon,p2_bp_saved,p2_ace_per_s,p2_df_per_s,p2_1st_r_ptwon,p2_2nd_r_ptwon,p2_bp_won,p2_tot_pt_won_s,p2_tot_pt_won_r,p2_tot_pt_won,p2_gms_won_s,p2_gms_won_r,p2_tot_gms_won
144899,Skopje CH,Clay,32,C,20240520,UN,Ryan Seggerman,U,NaN,24.7,UN,Kamil Majchrzak,R,183.0,28.3,3,SF,135.0,555.0,67.0,351.0,143.0,1,1,2,0.59,0.69,0.54,0.50,0.05,0.05,0.25,0.37,0.4,0.63,0.30,0.46,0.75,0.12,0.44,0.59,0.75,0.63,0.6,0.06,0.00,0.31,0.46,0.50,0.70,0.37,0.54,0.88,0.25,0.56
144900,Skopje CH,Clay,32,C,20240520,UN,Gerard Campana Lee,U,NaN,19.6,UN,Joel Schwaerzler,L,NaN,18.3,3,SF,184.0,349.0,144.0,664.0,48.0,1,0,1,0.61,0.60,0.46,0.58,0.03,0.06,0.27,0.50,0.5,0.55,0.37,0.46,0.64,0.13,0.40,0.58,0.73,0.50,0.5,0.03,0.04,0.40,0.54,0.42,0.63,0.45,0.54,0.87,0.36,0.60
144901,Skopje CH,Clay,32,C,20240520,UN,Kamil Majchrzak,R,183.0,28.3,UN,Joel Schwaerzler,L,NaN,18.3,3,F,81.0,351.0,143.0,664.0,48.0,0,0,0,0.59,0.62,0.42,0.60,0.08,0.02,0.33,0.32,0.5,0.54,0.33,0.45,0.56,0.11,0.33,0.55,0.67,0.68,0.5,0.06,0.00,0.38,0.58,0.40,0.67,0.46,0.55,0.89,0.44,0.67

In [49]:
# Add target variable
atp_win['result'] = 1  # 1 for p1 winner
atp_los['result'] = 0  # 0 for p1 loser

atp_win.shape, atp_los.shape

((144902, 56), (144902, 56))

In [50]:
# Concatenate the datasets for winners and losers
data_targeted = pd.concat([atp_win, atp_los], axis=0)
data_targeted.sort_values(by=['tourney_date', 'tourney_name', 'round', 'result'], inplace=True)
data_targeted.reset_index(drop=True, inplace=True)
data_targeted.tail(3)

,tourney_name,surface,draw_size,tourney_level,tourney_date,p1_seed,p1_name,p1_hand,p1_ht,p1_age,p2_seed,p2_name,p2_hand,p2_ht,p2_age,best_of,round,minutes,p1_rank,p1_rank_points,p2_rank,p2_rank_points,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p2_1st_in,p2_1st_ptwon,p2_2nd_ptwon,p2_bp_saved,p2_ace_per_s,p2_df_per_s,p2_1st_r_ptwon,p2_2nd_r_ptwon,p2_bp_won,p2_tot_pt_won_s,p2_tot_pt_won_r,p2_tot_pt_won,p2_gms_won_s,p2_gms_won_r,p2_tot_gms_won,result
289801,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Gerard Campana Lee,U,NaN,19.6,3,SF,184.0,664.0,48.0,349.0,144.0,0,1,1,0.58,0.73,0.50,0.5,0.03,0.04,0.40,0.54,0.42,0.63,0.45,0.54,0.87,0.36,0.60,0.61,0.60,0.46,0.58,0.03,0.06,0.27,0.50,0.5,0.55,0.37,0.46,0.64,0.13,0.40,1
289802,Skopje CH,Clay,32,C,20240520,UN,Kamil Majchrzak,R,183.0,28.3,UN,Joel Schwaerzler,L,NaN,18.3,3,F,81.0,351.0,143.0,664.0,48.0,0,0,0,0.59,0.62,0.42,0.6,0.08,0.02,0.33,0.32,0.50,0.54,0.33,0.45,0.56,0.11,0.33,0.55,0.67,0.68,0.50,0.06,0.00,0.38,0.58,0.4,0.67,0.46,0.55,0.89,0.44,0.67,0
289803,Skopje CH,Clay,32,C,20240520,UN,Joel Schwaerzler,L,NaN,18.3,UN,Kamil Majchrzak,R,183.0,28.3,3,F,81.0,664.0,48.0,351.0,143.0,0,0,0,0.55,0.67,0.68,0.5,0.06,0.00,0.38,0.58,0.40,0.67,0.46,0.55,0.89,0.44,0.67,0.59,0.62,0.42,0.60,0.08,0.02,0.33,0.32,0.5,0.54,0.33,0.45,0.56,0.11,0.33,1

In [51]:
data_targeted.shape

(289804, 56)

In [52]:
# data_targeted.tail(4000)
data_targeted.iloc[284525:284532]

,tourney_name,surface,draw_size,tourney_level,tourney_date,p1_seed,p1_name,p1_hand,p1_ht,p1_age,p2_seed,p2_name,p2_hand,p2_ht,p2_age,best_of,round,minutes,p1_rank,p1_rank_points,p2_rank,p2_rank_points,p1_tiebreaks_w,p2_tiebreaks_w,tiebreaks,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p2_1st_in,p2_1st_ptwon,p2_2nd_ptwon,p2_bp_saved,p2_ace_per_s,p2_df_per_s,p2_1st_r_ptwon,p2_2nd_r_ptwon,p2_bp_won,p2_tot_pt_won_s,p2_tot_pt_won_r,p2_tot_pt_won,p2_gms_won_s,p2_gms_won_r,p2_tot_gms_won,result
284525,Miami Masters,Hard,128,M,20240318,UN,Alexander Shevchenko,R,NaN,23.2,UN,Daniel Elahi Galan,R,191.0,27.7,3,R128,176.0,58.0,924.0,84.0,712.0,1,1,2,0.60,0.72,0.39,0.64,0.09,0.07,0.24,0.77,0.38,0.59,0.44,0.52,0.78,0.28,0.53,0.63,0.76,0.23,0.62,0.06,0.02,0.28,0.61,0.36,0.56,0.41,0.48,0.72,0.22,0.47,1
284526,Miami Masters,Hard,128,M,20240318,UN,Felix Auger Aliassime,R,193.0,23.6,UN,Adam Walton,U,NaN,24.9,3,R128,120.0,36.0,1165.0,150.0,445.0,0,0,0,0.67,0.81,0.62,1.00,0.17,0.06,0.37,0.41,0.50,0.75,0.38,0.56,1.00,0.18,0.59,0.75,0.63,0.59,0.50,0.03,0.01,0.19,0.38,0.00,0.62,0.25,0.44,0.82,0.00,0.41,1
284527,Miami Masters,Hard,128,M,20240318,UN,Daniel Evans,R,175.0,33.8,UN,Lorenzo Sonego,R,191.0,28.8,3,R128,143.0,43.0,1066.0,53.0,955.0,0,0,0,0.57,0.70,0.55,0.50,0.01,0.05,0.23,0.64,0.29,0.63,0.36,0.49,0.85,0.15,0.50,0.68,0.77,0.36,0.71,0.14,0.01,0.30,0.45,0.50,0.64,0.37,0.51,0.85,0.15,0.50,1
284528,Miami Masters,Hard,128,M,20240318,UN,Sebastian Ofner,R,191.0,27.8,UN,Kei Nishikori,R,178.0,34.2,3,R128,79.0,40.0,1076.0,351.0,143.0,0,0,0,0.59,0.81,0.62,1.00,0.14,0.00,0.41,0.30,0.50,0.73,0.37,0.56,1.00,0.22,0.63,0.65,0.59,0.70,0.50,0.00,0.00,0.19,0.38,0.00,0.63,0.27,0.44,0.78,0.00,0.37,1
284529,Miami Masters,Hard,128,M,20240318,UN,Laslo Djere,R,188.0,28.7,UN,Coleman Wong,R,NaN,19.7,3,R128,141.0,35.0,1180.0,212.0,285.0,1,0,1,0.71,0.65,0.54,0.73,0.04,0.02,0.27,0.68,0.44,0.62,0.45,0.54,0.75,0.33,0.56,0.56,0.73,0.32,0.56,0.07,0.06,0.35,0.46,0.27,0.55,0.38,0.46,0.67,0.25,0.44,1
284530,Miami Masters,Hard,128,M,20240318,UN,Soon Woo Kwon,R,180.0,26.2,UN,Alexandre Muller,R,183.0,27.1,3,R128,89.0,863.0,20.0,85.0,709.0,1,0,1,0.68,0.77,0.71,0.67,0.08,0.00,0.26,0.57,0.50,0.75,0.37,0.56,0.91,0.20,0.59,0.67,0.74,0.43,0.50,0.06,0.03,0.23,0.29,0.33,0.63,0.25,0.44,0.80,0.09,0.41,1
284531,Miami Masters,Hard,128,M,20240318,UN,Daniel Altmaier,R,191.0,25.5,UN,Harold Mayot,R,178.0,22.1,3,R128,109.0,54.0,951.0,141.0,472.0,0,0,0,0.75,0.67,0.53,0.86,0.09,0.03,0.34,0.54,0.44,0.64,0.43,0.54,0.90,0.40,0.65,0.53,0.66,0.46,0.56,0.02,0.03,0.33,0.47,0.14,0.57,0.36,0.46,0.60,0.10,0.35,1

## Create train dataset for model development

In [53]:
# Drop unnecessary columns for model training
model_data = data_targeted.drop(['minutes', 'tourney_name', 'tourney_date', 'p1_name', 'p2_name', 'p1_tiebreaks_w', 'p2_tiebreaks_w', 'tiebreaks'], axis=1)
# model_data = model_data[:284528]  # Uncomment this line if you want to have data to test developed models
model_data.shape

(289804, 48)

In [54]:
# Delete all rows with NaN values in the dataset
model_data.isnull().sum().sum().item()

111704

In [55]:
model_data.dropna(inplace=True)
model_data.reset_index(drop=True, inplace=True)
model_data.shape

(214740, 48)

In [56]:
model_data.isnull().sum().sum().item()

0

In [57]:
# U stands for Unknown so we are not interested in such records as well
model_data['p1_hand'].unique()

array(['R', 'L', 'U'], dtype=object)

In [58]:
model_data.drop(model_data[(model_data['p1_hand'] == 'U') | (model_data['p2_hand'] == 'U')].index, inplace=True)
model_data.reset_index(drop=True, inplace=True)
model_data.shape

(211646, 48)

In [59]:
model_data.tail(3)

,surface,draw_size,tourney_level,p1_seed,p1_hand,p1_ht,p1_age,p2_seed,p2_hand,p2_ht,p2_age,best_of,round,p1_rank,p1_rank_points,p2_rank,p2_rank_points,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p2_1st_in,p2_1st_ptwon,p2_2nd_ptwon,p2_bp_saved,p2_ace_per_s,p2_df_per_s,p2_1st_r_ptwon,p2_2nd_r_ptwon,p2_bp_won,p2_tot_pt_won_s,p2_tot_pt_won_r,p2_tot_pt_won,p2_gms_won_s,p2_gms_won_r,p2_tot_gms_won,result
211643,Clay,32,C,S,R,180.0,22.6,UN,R,185.0,31.6,3,R16,286.0,193.0,387.0,124.0,0.73,0.48,0.42,0.17,0.04,0.00,0.36,0.53,0.18,0.47,0.40,0.42,0.38,0.22,0.29,0.78,0.64,0.47,0.82,0.03,0.01,0.52,0.58,0.83,0.60,0.53,0.58,0.78,0.62,0.71,0
211644,Clay,32,C,UN,R,183.0,28.3,UN,R,180.0,23.1,3,R16,351.0,143.0,356.0,139.0,0.55,0.81,0.63,0.80,0.05,0.01,0.27,0.50,0.60,0.73,0.36,0.55,0.92,0.25,0.60,0.61,0.73,0.50,0.40,0.03,0.04,0.19,0.37,0.20,0.64,0.27,0.45,0.75,0.08,0.40,1
211645,Clay,32,C,UN,R,185.0,31.6,S,R,180.0,22.6,3,R16,387.0,124.0,286.0,193.0,0.78,0.64,0.47,0.82,0.03,0.01,0.52,0.58,0.83,0.60,0.53,0.58,0.78,0.62,0.71,0.73,0.48,0.42,0.17,0.04,0.00,0.36,0.53,0.18,0.47,0.40,0.42,0.38,0.22,0.29,1

In [60]:
# Calculate difference between players

p1_lst = ['p1_ht', 'p1_age', 'p1_rank', 'p1_rank_points', 'p1_1st_in', 'p1_1st_ptwon',
          'p1_2nd_ptwon', 'p1_bp_saved', 'p1_ace_per_s', 'p1_df_per_s', 'p1_1st_r_ptwon',
          'p1_2nd_r_ptwon', 'p1_bp_won', 'p1_tot_pt_won_s', 'p1_tot_pt_won_r', 'p1_tot_pt_won',
          'p1_gms_won_s', 'p1_gms_won_r', 'p1_tot_gms_won']

p2_lst = ['p2_ht', 'p2_age', 'p2_rank', 'p2_rank_points', 'p2_1st_in', 'p2_1st_ptwon',
          'p2_2nd_ptwon', 'p2_bp_saved', 'p2_ace_per_s', 'p2_df_per_s', 'p2_1st_r_ptwon',
          'p2_2nd_r_ptwon', 'p2_bp_won', 'p2_tot_pt_won_s', 'p2_tot_pt_won_r', 'p2_tot_pt_won',
          'p2_gms_won_s', 'p2_gms_won_r', 'p2_tot_gms_won']

new_names = ['ht_diff', 'age_diff', 'rank_diff', 'rank_pts_diff', '1st_in_diff', '1st_ptwon_diff',
          '2nd_ptwon_diff', 'bp_saved_diff', 'ace_per_s_diff', 'df_per_s_diff', '1st_r_ptwon_diff',
          '2nd_r_ptwon_diff', 'bp_won_diff', 'tot_pt_won_s_diff', 'tot_pt_won_r_diff', 'tot_pt_won_diff',
          'gms_won_s_diff', 'gms_won_r_diff', 'tot_gms_won_diff']

In [61]:
for i, j, n in zip(p1_lst, p2_lst, new_names):
    model_data[n] = round(model_data[i] - model_data[j], 2)
    model_data.drop([i, j], axis=1, inplace=True)
    
model_data.shape

(211646, 29)

In [62]:
model_data.tail(3)

,surface,draw_size,tourney_level,p1_seed,p1_hand,p2_seed,p2_hand,best_of,round,result,ht_diff,age_diff,rank_diff,rank_pts_diff,1st_in_diff,1st_ptwon_diff,2nd_ptwon_diff,bp_saved_diff,ace_per_s_diff,df_per_s_diff,1st_r_ptwon_diff,2nd_r_ptwon_diff,bp_won_diff,tot_pt_won_s_diff,tot_pt_won_r_diff,tot_pt_won_diff,gms_won_s_diff,gms_won_r_diff,tot_gms_won_diff
211643,Clay,32,C,S,R,UN,R,3,R16,0,-5.0,-9.0,-101.0,69.0,-0.05,-0.16,-0.05,-0.65,0.01,-0.01,-0.16,-0.05,-0.65,-0.13,-0.13,-0.16,-0.40,-0.40,-0.42
211644,Clay,32,C,UN,R,UN,R,3,R16,1,3.0,5.2,-5.0,4.0,-0.06,0.08,0.13,0.40,0.02,-0.03,0.08,0.13,0.40,0.09,0.09,0.10,0.17,0.17,0.20
211645,Clay,32,C,UN,R,S,R,3,R16,1,5.0,9.0,101.0,-69.0,0.05,0.16,0.05,0.65,-0.01,0.01,0.16,0.05,0.65,0.13,0.13,0.16,0.40,0.40,0.42

In [63]:
model_data.to_csv('../../data/train_data/atp_train.csv', index=False)  # Save data for model training

### Create database with historical matches

In [64]:
atp_database = data_targeted[['tourney_name', 'tourney_date', 'surface', 'tourney_level', 'round', 
                              'p1_seed', 'p1_name', 'p2_seed', 'p2_name', 'result', 'minutes', 
                              'p1_1st_in', 'p1_1st_ptwon', 'p1_2nd_ptwon', 'p1_bp_saved', 
                              'p1_ace_per_s', 'p1_df_per_s', 'p1_1st_r_ptwon', 'p1_2nd_r_ptwon', 
                              'p1_bp_won', 'p1_tot_pt_won_s', 'p1_tot_pt_won_r', 'p1_tot_pt_won', 
                              'p1_gms_won_s', 'p1_gms_won_r', 'p1_tot_gms_won', 'p1_tiebreaks_w', 'tiebreaks']]
atp_database.shape

(289804, 28)

In [65]:
atp_database.tail()

,tourney_name,tourney_date,surface,tourney_level,round,p1_seed,p1_name,p2_seed,p2_name,result,minutes,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p1_tiebreaks_w,tiebreaks
289799,Skopje CH,20240520,Clay,C,SF,UN,Gerard Campana Lee,UN,Joel Schwaerzler,0,184.0,0.61,0.60,0.46,0.58,0.03,0.06,0.27,0.50,0.50,0.55,0.37,0.46,0.64,0.13,0.40,1,1
289800,Skopje CH,20240520,Clay,C,SF,UN,Kamil Majchrzak,UN,Ryan Seggerman,1,135.0,0.59,0.75,0.63,0.60,0.06,0.00,0.31,0.46,0.50,0.70,0.37,0.54,0.88,0.25,0.56,1,2
289801,Skopje CH,20240520,Clay,C,SF,UN,Joel Schwaerzler,UN,Gerard Campana Lee,1,184.0,0.58,0.73,0.50,0.50,0.03,0.04,0.40,0.54,0.42,0.63,0.45,0.54,0.87,0.36,0.60,0,1
289802,Skopje CH,20240520,Clay,C,F,UN,Kamil Majchrzak,UN,Joel Schwaerzler,0,81.0,0.59,0.62,0.42,0.60,0.08,0.02,0.33,0.32,0.50,0.54,0.33,0.45,0.56,0.11,0.33,0,0
289803,Skopje CH,20240520,Clay,C,F,UN,Joel Schwaerzler,UN,Kamil Majchrzak,1,81.0,0.55,0.67,0.68,0.50,0.06,0.00,0.38,0.58,0.40,0.67,0.46,0.55,0.89,0.44,0.67,0,0

In [66]:
atp_database.isnull().sum()

tourney_name           0
tourney_date           0
surface                0
tourney_level          0
round                  0
p1_seed                0
p1_name                0
p2_seed                0
p2_name                0
result                 0
minutes            11782
p1_1st_in              0
p1_1st_ptwon           0
p1_2nd_ptwon           0
p1_bp_saved            0
p1_ace_per_s           0
p1_df_per_s            0
p1_1st_r_ptwon         0
p1_2nd_r_ptwon         0
p1_bp_won              0
p1_tot_pt_won_s        0
p1_tot_pt_won_r        0
p1_tot_pt_won          0
p1_gms_won_s           0
p1_gms_won_r           0
p1_tot_gms_won         0
p1_tiebreaks_w         0
tiebreaks              0
dtype: int64

In [67]:
atp_database['minutes'][2000000:].isnull().sum().item()
# It means that the most recent records have all the data available.

0

In [68]:
# Replace missing values in 'minutes' column with 0 for the older records
atp_database.loc[:, 'minutes'] = atp_database['minutes'].astype(float)
atp_database.loc[:, 'minutes'] = atp_database['minutes'].fillna(0)
atp_database.isnull().sum().sum().item()

0

In [69]:
atp_database.dtypes

tourney_name         object
tourney_date          int64
surface              object
tourney_level        object
round              category
p1_seed              object
p1_name              object
p2_seed              object
p2_name              object
result                int64
minutes             float64
p1_1st_in           float64
p1_1st_ptwon        float64
p1_2nd_ptwon        float64
p1_bp_saved         float64
p1_ace_per_s        float64
p1_df_per_s         float64
p1_1st_r_ptwon      float64
p1_2nd_r_ptwon      float64
p1_bp_won           float64
p1_tot_pt_won_s     float64
p1_tot_pt_won_r     float64
p1_tot_pt_won       float64
p1_gms_won_s        float64
p1_gms_won_r        float64
p1_tot_gms_won      float64
p1_tiebreaks_w        int64
tiebreaks             int64
dtype: object

In [70]:
# Convert 'tourney_date' column to date format
atp_database = atp_database.astype({'tourney_date': 'string'})
atp_database['tourney_date'] = pd.to_datetime(atp_database['tourney_date'])
atp_database.tail(3)

,tourney_name,tourney_date,surface,tourney_level,round,p1_seed,p1_name,p2_seed,p2_name,result,minutes,p1_1st_in,p1_1st_ptwon,p1_2nd_ptwon,p1_bp_saved,p1_ace_per_s,p1_df_per_s,p1_1st_r_ptwon,p1_2nd_r_ptwon,p1_bp_won,p1_tot_pt_won_s,p1_tot_pt_won_r,p1_tot_pt_won,p1_gms_won_s,p1_gms_won_r,p1_tot_gms_won,p1_tiebreaks_w,tiebreaks
289801,Skopje CH,2024-05-20,Clay,C,SF,UN,Joel Schwaerzler,UN,Gerard Campana Lee,1,184.0,0.58,0.73,0.50,0.5,0.03,0.04,0.40,0.54,0.42,0.63,0.45,0.54,0.87,0.36,0.60,0,1
289802,Skopje CH,2024-05-20,Clay,C,F,UN,Kamil Majchrzak,UN,Joel Schwaerzler,0,81.0,0.59,0.62,0.42,0.6,0.08,0.02,0.33,0.32,0.50,0.54,0.33,0.45,0.56,0.11,0.33,0,0
289803,Skopje CH,2024-05-20,Clay,C,F,UN,Joel Schwaerzler,UN,Kamil Majchrzak,1,81.0,0.55,0.67,0.68,0.5,0.06,0.00,0.38,0.58,0.40,0.67,0.46,0.55,0.89,0.44,0.67,0,0

In [71]:
atp_database.rename(columns = {'p1_seed': 'player_seed', 'p1_name': 'player_name', 'p2_seed': 'opponent_seed', 
                                'p2_name': 'opponent_name','p1_1st_in': '1st_in', 'p1_1st_ptwon': '1st_ptwon',
                                'p1_2nd_ptwon': '2nd_ptwon', 'p1_bp_saved': 'bp_saved', 
                                'p1_ace_per_s': 'ace_per_s', 'p1_df_per_s': 'df_per_s', 
                                'p1_1st_r_ptwon': '1st_r_ptwon', 'p1_2nd_r_ptwon': '2nd_r_ptwon', 
                                'p1_bp_won': 'bp_won', 'p1_tot_pt_won_s': 'tot_pt_won_s',
                                'p1_tot_pt_won_r': 'tot_pt_won_r', 'p1_tot_pt_won': 'tot_pt_won',
                                'p1_gms_won_s': 'gms_won_s', 'p1_gms_won_r': 'gms_won_r',
                                'p1_tot_gms_won': 'tot_gms_won', 'p1_tiebreaks_w': 'tiebreaks_w'}, inplace=True)
atp_database.tail(3)

,tourney_name,tourney_date,surface,tourney_level,round,player_seed,player_name,opponent_seed,opponent_name,result,minutes,1st_in,1st_ptwon,2nd_ptwon,bp_saved,ace_per_s,df_per_s,1st_r_ptwon,2nd_r_ptwon,bp_won,tot_pt_won_s,tot_pt_won_r,tot_pt_won,gms_won_s,gms_won_r,tot_gms_won,tiebreaks_w,tiebreaks
289801,Skopje CH,2024-05-20,Clay,C,SF,UN,Joel Schwaerzler,UN,Gerard Campana Lee,1,184.0,0.58,0.73,0.50,0.5,0.03,0.04,0.40,0.54,0.42,0.63,0.45,0.54,0.87,0.36,0.60,0,1
289802,Skopje CH,2024-05-20,Clay,C,F,UN,Kamil Majchrzak,UN,Joel Schwaerzler,0,81.0,0.59,0.62,0.42,0.6,0.08,0.02,0.33,0.32,0.50,0.54,0.33,0.45,0.56,0.11,0.33,0,0
289803,Skopje CH,2024-05-20,Clay,C,F,UN,Joel Schwaerzler,UN,Kamil Majchrzak,1,81.0,0.55,0.67,0.68,0.5,0.06,0.00,0.38,0.58,0.40,0.67,0.46,0.55,0.89,0.44,0.67,0,0

# Only if you want to test developed models

#### Separate historical database and matches to predict and save the data in 2 different .csv files. Enter your own path instead of `?` while saving them.

In [72]:
# # Starting Acapulco CH Hard 32 C 20240415 (284528)

# matches_to_predict = atp_database[284528:]
# atp_database = atp_database[:284528]

In [73]:
# atp_database.tail(3)

In [74]:
# matches_to_predict.head(3)

In [75]:
# atp_database.to_csv('?/atp_matches_database.csv', index=False)

In [76]:
# matches_to_predict.to_csv('?/matches_to_predict_atp.csv', index=False)